# Generated by Django 6.0.2 on 2026-04-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_walkin',
        ),
    ]
